# docker-compose.yml
version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: kong-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - kong-net

  kong:
    image: kong/kong-gateway:latest
    container_name: kong
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: ${POSTGRES_USER}
      KONG_PG_PASSWORD: ${POSTGRES_PASSWORD}
      KONG_ADMIN_LISTEN: 0.0.0.0:${KONG_ADMIN_PORT}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    command: ["kong", "docker-start"]
    ports:
      - "${KONG_PROXY_HTTP}:8000"
      - "${KONG_PROXY_HTTPS}:8443"
      - "${KONG_ADMIN_PORT}:${KONG_ADMIN_PORT}"
      - "${KONG_ADMIN_HTTPS}:8444"
    networks:
      - kong-net

  konga:
    image: pantsel/konga:latest
    container_name: konga
    depends_on:
      - kong
    ports:
      - "${KONGA_HOST_PORT}:1337"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
